name: Push pytorch/pytorch:2.2.1-cuda12.1-cudnn8-runtime to Alibaba Cloud Registry

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '2.2.1-cuda12.1-cudnn8-runtime'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Alibaba Cloud Registry
      uses: docker/login-action@v1
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIBABA_CLOUD_USERNAME }}
        password: ${{ secrets.ALIBABA_CLOUD_PASSWORD }}

    - name: Pull PyTorch image
      run: |
        docker pull pytorch/pytorch:${{ github.event.inputs.image_tag }}

    - name: Tag the image
      run: |
        docker tag pytorch/pytorch:${{ github.event.inputs.image_tag }} registry.cn-hangzhou.aliyuncs.com/fuli1001/pytorch:${{ github.event.inputs.image_tag }}

    - name: Push the image
      run: |
        docker push registry.cn-hangzhou.aliyuncs.com/fuli1001/pytorch:${{ github.event.inputs.image_tag }}
