name: Push docker images to Alibaba Cloud Registry

on:
  workflow_dispatch:
    inputs:
      push_python:
        description: 'Push python image'
        required: false
        type: boolean
        default: true
      python_tag:
        description: 'python image tag'
        required: true
        default: '3.12-slim'
      push_python_310:
        description: 'Push python:3.10-slim-bullseye image'
        required: false
        type: boolean
        default: true
      python_310-slim-bullseye:
        description: 'python:3.10-slim-bullseye'
        required: true
        default: 'python:3.10-slim-bullseye'
      push_pytorch:
        description: 'Push pytorch image'
        required: false
        type: boolean
        default: true
      pytorch_tag:
        description: 'pytorch image tag'
        required: true
        default: '2.2.1-cuda12.1-cudnn8-runtime'
      push_node:
        description: 'Push node image'
        required: false
        type: boolean
        default: true
      node_tag:
        description: 'node image tag'
        required: true
        default: 'lts-slim'
      push_mongo:
        description: 'Push mongo image'
        required: false
        type: boolean
        default: true
      mongo_tag:
        description: 'mongo image tag'
        required: true
        default: '4.4'
      push_mongo_express:
        description: 'Push mongo-express image'
        required: false
        type: boolean
        default: true
      mongo_express_tag:
        description: 'mongo-express image tag'
        required: true
        default: 'latest'
      push_cloudflared:
        description: 'Push cloudflared image'
        required: false
        type: boolean
        default: true
      cloudflared_latest:
        description: 'cloudflared:latest'
        required: true
        default: 'cloudflared:latest'
      push_postgres:
        description: 'Push postgres image'
        required: false
        type: boolean
        default: true
      postgres_tag:
        description: 'postgres image tag'
        required: true
        default: '15-alpine'
      push_radarr:
        description: 'Push radarr image'
        required: false
        type: boolean
        default: true
      radarr_tag:
        description: 'radarr image tag'
        required: true
        default: 'latest'
      push_prowlarr:
        description: 'Push prowlarr image'
        required: false
        type: boolean
        default: true
      prowlarr_tag:
        description: 'prowlarr image tag'
        required: true
        default: 'latest'
      push_bazarr:
        description: 'Push bazarr image'
        required: false
        type: boolean
        default: true
      bazarr_tag:
        description: 'bazarr image tag'
        required: true
        default: 'latest'
      push_qbittorrent:
        description: 'Push qbittorrent image'
        required: false
        type: boolean
        default: true
      qbittorrent_tag:
        description: 'qbittorrent image tag'
        required: true
        default: 'latest'
      registry:
        description: 'Alibaba Cloud Registry address (e.g., registry.cn-hangzhou.aliyuncs.com)'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      namespace:
        description: 'Alibaba Cloud Registry namespace (e.g., fuli1001)'
        required: true
        default: 'fuli1001'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Alibaba Cloud Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ github.event.inputs.registry }}
        username: ${{ secrets.ALIBABA_CLOUD_USERNAME }}
        password: ${{ secrets.ALIBABA_CLOUD_PASSWORD }}

    - name: Pull, tag, and push python image
      if: ${{ github.event.inputs.push_python == 'true' }}
      run: |
        SOURCE_IMAGE="python:${{ github.event.inputs.python_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/python:${{ github.event.inputs.python_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push python image
      if: ${{ github.event.inputs.push_python_310 == 'true' }}
      run: |
        SOURCE_IMAGE="${{ github.event.inputs.python_310-slim-bullseye }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/${{ github.event.inputs.python_310-slim-bullseye }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push pytorch image
      if: ${{ github.event.inputs.push_pytorch == 'true' }}
      run: |
        SOURCE_IMAGE="pytorch:${{ github.event.inputs.pytorch_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/pytorch:${{ github.event.inputs.pytorch_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push node image
      if: ${{ github.event.inputs.push_node == 'true' }}
      run: |
        SOURCE_IMAGE="node:${{ github.event.inputs.node_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/node:${{ github.event.inputs.node_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push mongo image
      if: ${{ github.event.inputs.push_mongo == 'true' }}
      run: |
        SOURCE_IMAGE="mongo:${{ github.event.inputs.mongo_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/mongo:${{ github.event.inputs.mongo_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push mongo-express image
      if: ${{ github.event.inputs.push_mongo_express == 'true' }}
      run: |
        SOURCE_IMAGE="mongo-express:${{ github.event.inputs.mongo_express_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/mongo-express:${{ github.event.inputs.mongo_express_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push cloudflared image
      if: ${{ github.event.inputs.push_cloudflared == 'true' }}
      run: |
        SOURCE_IMAGE="cloudflare/${{ github.event.inputs.cloudflared_latest }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/${{ github.event.inputs.cloudflared_latest }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push postgres image
      if: ${{ github.event.inputs.push_postgres == 'true' }}
      run: |
        SOURCE_IMAGE="postgres:${{ github.event.inputs.postgres_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/postgres:${{ github.event.inputs.postgres_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push radarr image
      if: ${{ github.event.inputs.push_radarr == 'true' }}
      run: |
        SOURCE_IMAGE="ghcr.io/linuxserver/radarr:${{ github.event.inputs.radarr_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/radarr:${{ github.event.inputs.radarr_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push prowlarr image
      if: ${{ github.event.inputs.push_prowlarr == 'true' }}
      run: |
        SOURCE_IMAGE="ghcr.io/linuxserver/prowlarr:${{ github.event.inputs.prowlarr_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/prowlarr:${{ github.event.inputs.prowlarr_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push bazarr image
      if: ${{ github.event.inputs.push_bazarr == 'true' }}
      run: |
        SOURCE_IMAGE="ghcr.io/linuxserver/bazarr:${{ github.event.inputs.bazarr_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/bazarr:${{ github.event.inputs.bazarr_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

    - name: Pull, tag, and push qbittorrent image
      if: ${{ github.event.inputs.push_qbittorrent == 'true' }}
      run: |
        SOURCE_IMAGE="ghcr.io/linuxserver/qbittorrent:${{ github.event.inputs.qbittorrent_tag }}"
        TARGET_IMAGE="${{ github.event.inputs.registry }}/${{ github.event.inputs.namespace }}/qbittorrent:${{ github.event.inputs.qbittorrent_tag }}"

        docker pull $SOURCE_IMAGE
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE
